import '../globals.css';
import { Toaster } from "@/components/ui/toaster"

const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='html4' >
            <div>
                {children}
                <Toaster />
            </div>
        </div>
    )
}
