import '../globals.css';

const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='html4' >
            <div>
                {children}
            </div>
        </div>
    )
}
